version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=Password1
      - discovery.type=single-node
      - bootstrap.memory_lock=true

  mongodb:
    image: mongo:5.0.8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=auditlog
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    volumes:
      - mongodb:/data/db
      - mongodbconfig:/data/configdb

  unroutedmessageservice:
    image: ${DOCKER_REGISTRY-}unroutedmessageservice
    restart: always
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: UnroutedMessageService/Dockerfile

  taskmanagementapi:
    image: ${DOCKER_REGISTRY-}taskmanagementapi
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: TaskManagementApi/Dockerfile

  searchapi:
    image: ${DOCKER_REGISTRY-}searchapi
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - rabbitmq
      - elasticsearch
    build:
      context: .
      dockerfile: SearchApi/Dockerfile

  auditlogworkerservice:
    image: ${DOCKER_REGISTRY-}auditlogworkerservice
    restart: always
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: AuditLogWorkerService/Dockerfile

  auditlogapi:
    image: ${DOCKER_REGISTRY-}auditlogapi
    restart: always
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: AuditLogApi/Dockerfile

volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local
  elasticsearch:
    driver: local
  mongodb:
    driver: local
  mongodbconfig:
    driver: local


